FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install


FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build arguments for Next.js public environment variables
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_PAYMENT_QR_BANK_CODE
ARG NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NUMBER
ARG NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NAME
ARG NEXT_PUBLIC_PAYMENT_QR_TEMPLATE

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_PAYMENT_QR_BANK_CODE=$NEXT_PUBLIC_PAYMENT_QR_BANK_CODE
ENV NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NUMBER=$NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NUMBER
ENV NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NAME=$NEXT_PUBLIC_PAYMENT_QR_ACCOUNT_NAME
ENV NEXT_PUBLIC_PAYMENT_QR_TEMPLATE=$NEXT_PUBLIC_PAYMENT_QR_TEMPLATE
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]
