export interface DomainItem {
  id: string;
  nameVi: string;
  nameEn: string;
  descVi: string;
  descEn: string;
  iconType: string;
  color: string;
}

export interface RoleOption {
  id: string;
  domainId: string;
  titleEn: string;
  titleVi: string;
  descVi: string;
  descEn: string;
}

export const ONBOARDING_DOMAINS: DomainItem[] = [
  {
    id: "swe",
    nameVi: "Kỹ thuật & Phần mềm (Software & Engineering)",
    nameEn: "Software & Engineering",
    descVi: "Frontend, Backend, Full Stack, SRE, DevOps, Solutions Architect, Mobile, QA...",
    descEn: "Frontend, Backend, Full Stack, SRE, DevOps, Solutions Architect, Mobile, QA...",
    iconType: "code",
    color: "#3b82f6",
  },
  {
    id: "ai_data",
    nameVi: "Trí tuệ Nhân tạo & Dữ liệu (AI, Data & Analytics)",
    nameEn: "AI, Data & Analytics",
    descVi: "AI Engineer, Machine Learning, Data Science, Data Engineer, Data Analyst, Quant...",
    descEn: "AI Engineer, Machine Learning, Data Science, Data Engineer, Data Analyst, Quant...",
    iconType: "brain",
    color: "#8b5cf6",
  },
  {
    id: "product",
    nameVi: "Quản trị Sản phẩm & Chiến lược (Product & Strategy)",
    nameEn: "Product & Strategy",
    descVi: "Product Manager (PM), TPM, Program Manager, BizOps, Business Analyst...",
    descEn: "Product Manager (PM), TPM, Program Manager, BizOps, Business Analyst...",
    iconType: "target",
    color: "#f59e0b",
  },
  {
    id: "security",
    nameVi: "An toàn Thông tin & An ninh mạng (Cybersecurity)",
    nameEn: "Cybersecurity & InfoSec",
    descVi: "Security Engineer, Security Analyst, Ethical Hacker, Pentest, IAM, GRC...",
    descEn: "Security Engineer, Security Analyst, Ethical Hacker, Pentest, IAM, GRC...",
    iconType: "shield",
    color: "#ef4444",
  },
  {
    id: "finance",
    nameVi: "Tài chính, Đầu tư & Quỹ (Finance & Investment)",
    nameEn: "Finance & Investment",
    descVi: "Investment Banking, Finance & Strategy, Private Equity, Venture Capital...",
    descEn: "Investment Banking, Finance & Strategy, Private Equity, Venture Capital...",
    iconType: "landmark",
    color: "#10b981",
  },
  {
    id: "design",
    nameVi: "Thiết kế Sản phẩm & Trải nghiệm (UI/UX & Design)",
    nameEn: "Product & Visual Design",
    descVi: "Product Designer, Visual Designer, User Researcher, Design Manager...",
    descEn: "Product Designer, Visual Designer, User Researcher, Design Manager...",
    iconType: "palette",
    color: "#ec4899",
  },
  {
    id: "business",
    nameVi: "Kinh doanh, Tiếp thị & Nhân tài (Business, Marketing & HR)",
    nameEn: "Business, Marketing & HR",
    descVi: "Marketing Manager, Sales Rep, Business Development, Account Manager, Recruiter...",
    descEn: "Marketing Manager, Sales Rep, Business Development, Account Manager, Recruiter...",
    iconType: "trending-up",
    color: "#06b6d4",
  },
];

export const COMPREHENSIVE_ROLES: RoleOption[] = [
  // 1. Software & Engineering (13 roles)
  {
    id: "software-engineer",
    domainId: "swe",
    titleEn: "Software Engineer",
    titleVi: "Kỹ sư Phần mềm (Software Engineer)",
    descVi: "Lập trình viên phát triển hệ thống phần mềm, thuật toán và kiến trúc mã nguồn.",
    descEn: "Core software engineering, algorithms, system architecture and coding rounds.",
  },
  {
    id: "frontend-engineer",
    domainId: "swe",
    titleEn: "Frontend Engineer",
    titleVi: "Kỹ sư Frontend (Frontend Engineer)",
    descVi: "Giao diện web hiện đại, React/Next.js, TypeScript, tối ưu Core Web Vitals.",
    descEn: "Modern web interfaces, React/Next.js, TypeScript, and Core Web Vitals.",
  },
  {
    id: "backend-engineer",
    domainId: "swe",
    titleEn: "Backend Engineer",
    titleVi: "Kỹ sư Backend (Backend Engineer)",
    descVi: "API hiệu năng cao, Microservices, Spring Boot, Go, Node.js, Database SQL/NoSQL.",
    descEn: "High-performance APIs, Microservices, Spring Boot, Go, Databases and Caching.",
  },
  {
    id: "mobile-engineer",
    domainId: "swe",
    titleEn: "Mobile Engineer",
    titleVi: "Kỹ sư Lập trình Di động (Mobile Engineer)",
    descVi: "Phát triển ứng dụng iOS (Swift) và Android (Kotlin) hoặc Flutter/React Native.",
    descEn: "Mobile app engineering with iOS (Swift), Android (Kotlin), or Cross-platform.",
  },
  {
    id: "solutions-architect",
    domainId: "swe",
    titleEn: "Solutions Architect",
    titleVi: "Kiến trúc sư Giải pháp (Solutions Architect)",
    descVi: "Thiết kế kiến trúc hệ thống tổng thể, điện toán đám mây và tích hợp doanh nghiệp.",
    descEn: "End-to-end cloud solutions architecture, scalability and enterprise integration.",
  },
  {
    id: "forward-deployed-engineer",
    domainId: "swe",
    titleEn: "Forward Deployed Engineer",
    titleVi: "Kỹ sư FDE (Forward Deployed Engineer)",
    descVi: "Cầu nối kỹ thuật và khách hàng lớn, triển khai phần mềm trực tiếp tại thực địa.",
    descEn: "Customer-facing technical engineering, field deployment and client integrations.",
  },
  {
    id: "engineering-manager",
    domainId: "swe",
    titleEn: "Engineering Manager",
    titleVi: "Quản lý Kỹ thuật (Engineering Manager)",
    descVi: "Lãnh đạo đội ngũ kỹ sư, quản lý lộ trình phát triển và văn hóa kỹ thuật.",
    descEn: "Technical leadership, team scaling, roadmap execution and engineer mentoring.",
  },
  {
    id: "site-reliability-engineer",
    domainId: "swe",
    titleEn: "Site Reliability Engineer",
    titleVi: "Kỹ sư SRE (Site Reliability Engineer)",
    descVi: "Vận hành hệ thống chịu tải, giám sát SLO/SLA, tự động hóa và ứng cứu sự cố.",
    descEn: "Reliability engineering, SLO/SLA monitoring, automation and incident management.",
  },
  {
    id: "devops",
    domainId: "swe",
    titleEn: "DevOps",
    titleVi: "Kỹ sư DevOps (DevOps Engineer)",
    descVi: "Tự động hóa CI/CD, hạ tầng Kubernetes, Docker, Terraform và đám mây AWS/GCP.",
    descEn: "CI/CD pipelines, Kubernetes orchestration, Infrastructure as Code, Cloud AWS/GCP.",
  },
  {
    id: "qa-engineer",
    domainId: "swe",
    titleEn: "QA Engineer",
    titleVi: "Kỹ sư Đảm bảo Chất lượng (QA Engineer)",
    descVi: "Quy trình kiểm thử chất lượng phần mềm, xây dựng kịch bản và tự động hóa test.",
    descEn: "Software quality assurance, test strategy, automated testing pipelines.",
  },
  {
    id: "test-engineer",
    domainId: "swe",
    titleEn: "Test Engineer",
    titleVi: "Kỹ sư Kiểm thử Phần mềm (Test Engineer)",
    descVi: "Kiểm thử tự động, kiểm thử hiệu năng và kiểm thử hồi quy hệ thống.",
    descEn: "Automated test suites, performance testing, stress testing and regression.",
  },
  {
    id: "hardware-engineer",
    domainId: "swe",
    titleEn: "Hardware Engineer",
    titleVi: "Kỹ sư Phần cứng (Hardware Engineer)",
    descVi: "Thiết kế vi mạch, hệ thống nhúng, vi điều khiển và phần cứng IoT.",
    descEn: "Circuit design, embedded systems, microcontrollers, and IoT hardware.",
  },
  {
    id: "deployment-strategist",
    domainId: "swe",
    titleEn: "Deployment Strategist",
    titleVi: "Chuyên viên Chiến lược Triển khai (Deployment Strategist)",
    descVi: "Chiến lược phân phối, đưa sản phẩm và hệ thống phức tạp vào vận hành thực tế.",
    descEn: "Enterprise rollout strategies, operational transformation and software adoption.",
  },

  // 2. AI, Data & Analytics (8 roles)
  {
    id: "ai-engineer",
    domainId: "ai_data",
    titleEn: "AI Engineer",
    titleVi: "Kỹ sư Trí tuệ Nhân tạo (AI Engineer)",
    descVi: "Xây dựng ứng dụng GenAI, mô hình ngôn ngữ lớn (LLM), RAG và AI Agent.",
    descEn: "Generative AI applications, Large Language Models (LLM), RAG and AI Agents.",
  },
  {
    id: "machine-learning-engineer",
    domainId: "ai_data",
    titleEn: "Machine Learning Engineer",
    titleVi: "Kỹ sư Học máy (Machine Learning Engineer)",
    descVi: "Huấn luyện mô hình, Feature Engineering, triển khai MLOps và phục vụ suy luận.",
    descEn: "Model training, feature engineering, MLOps deployment and inference pipelines.",
  },
  {
    id: "data-scientist",
    domainId: "ai_data",
    titleEn: "Data Scientist",
    titleVi: "Nhà khoa học Dữ liệu (Data Scientist)",
    descVi: "Mô hình hóa thống kê, thử nghiệm A/B, Machine Learning và khai phá tri thức.",
    descEn: "Statistical modeling, predictive analytics, A/B experiments and machine learning.",
  },
  {
    id: "data-engineer",
    domainId: "ai_data",
    titleEn: "Data Engineer",
    titleVi: "Kỹ sư Dữ liệu (Data Engineer)",
    descVi: "Xây dựng Data Pipeline, Data Lake, Apache Spark, Kafka, Airflow và Snowflake.",
    descEn: "Big Data pipelines, distributed processing with Spark, Kafka, Snowflake.",
  },
  {
    id: "data-analyst",
    domainId: "ai_data",
    titleEn: "Data Analyst",
    titleVi: "Chuyên viên Phân tích Dữ liệu (Data Analyst)",
    descVi: "Khai thác SQL, phân tích Cohort, trực quan hóa Power BI/Tableau và Business Insights.",
    descEn: "SQL querying, Cohort analysis, Power BI/Tableau dashboards and business insights.",
  },
  {
    id: "product-analyst",
    domainId: "ai_data",
    titleEn: "Product Analyst",
    titleVi: "Chuyên viên Phân tích Sản phẩm (Product Analyst)",
    descVi: "Đo lường chỉ số sản phẩm, tỷ lệ giữ chân (Retention), chuyển đổi và phễu người dùng.",
    descEn: "Product telemetry, retention metrics, funnel analytics and growth experimentation.",
  },
  {
    id: "quantitative-researcher",
    domainId: "ai_data",
    titleEn: "Quantitative Researcher",
    titleVi: "Nhà nghiên cứu Định lượng (Quantitative Researcher)",
    descVi: "Mô hình toán học định lượng, chiến lược tín hiệu alpha và thống kê tài chính.",
    descEn: "Mathematical trading signals, alpha generation, econometric and financial statistics.",
  },
  {
    id: "quantitative-developer",
    domainId: "ai_data",
    titleEn: "Quantitative Developer",
    titleVi: "Kỹ sư Lập trình Định lượng (Quantitative Developer)",
    descVi: "Hệ thống giao dịch tự động tần suất cao (HFT), thuật toán C++/Python độ trễ thấp.",
    descEn: "High-frequency trading infrastructure, low-latency algorithms in C++/Python.",
  },

  // 3. Product & Program Management (7 roles)
  {
    id: "product-manager",
    domainId: "product",
    titleEn: "Product Manager",
    titleVi: "Quản lý Sản phẩm (Product Manager)",
    descVi: "Chiến lược sản phẩm (Product Sense), Roadmap, ưu tiên tính năng và đo lường OKRs.",
    descEn: "Product sense, product strategy, roadmap prioritization, and execution.",
  },
  {
    id: "technical-program-manager",
    domainId: "product",
    titleEn: "Technical Program Manager",
    titleVi: "Quản lý Chương trình Kỹ thuật (Technical Program Manager)",
    descVi: "Điều phối các chương trình kỹ thuật đa chức năng, kiến trúc kỹ thuật và rủi ro.",
    descEn: "Cross-functional technical program leadership, system dependencies and delivery.",
  },
  {
    id: "program-manager",
    domainId: "product",
    titleEn: "Program Manager",
    titleVi: "Quản lý Chương trình (Program Manager)",
    descVi: "Quản trị danh mục dự án, tối ưu hóa quy trình tổ chức và quản trị các bên liên quan.",
    descEn: "Portfolio project execution, operational excellence and stakeholder alignment.",
  },
  {
    id: "bizops-strategy",
    domainId: "product",
    titleEn: "BizOps & Strategy",
    titleVi: "Chiến lược & Vận hành Doanh nghiệp (BizOps & Strategy)",
    descVi: "Phân tích chiến lược kinh doanh, tối ưu hóa vận hành và mở rộng thị trường.",
    descEn: "Corporate strategic initiatives, operational modeling and business scaling.",
  },
  {
    id: "business-analyst",
    domainId: "product",
    titleEn: "Business Analyst",
    titleVi: "Chuyên viên Phân tích Nghiệp vụ (Business Analyst)",
    descVi: "Bóc tách yêu cầu nghiệp vụ (BRD/FRD), mô hình hóa quy trình và cầu nối kinh doanh - công nghệ.",
    descEn: "Requirements engineering (BRD/FRD), process modeling and business-IT bridge.",
  },
  {
    id: "chief-of-staff",
    domainId: "product",
    titleEn: "Chief of Staff",
    titleVi: "Chánh Văn phòng / Cố vấn Điều hành (Chief of Staff)",
    descVi: "Cánh tay phải đắc lực của CEO/Ban Giám đốc, điều phối chiến lược và vận hành cấp cao.",
    descEn: "Executive leadership partner, strategic alignment and cross-company orchestration.",
  },
  {
    id: "management-consultant",
    domainId: "product",
    titleEn: "Management Consultant",
    titleVi: "Chuyên viên Tư vấn Quản trị (Management Consultant)",
    descVi: "Giải quyết vấn đề chiến lược (Case Interview), tái cấu trúc doanh nghiệp và M&A.",
    descEn: "Management consulting frameworks, business turnaround and M&A advisory.",
  },

  // 4. Cybersecurity & Security (8 roles)
  {
    id: "security-engineer",
    domainId: "security",
    titleEn: "Security Engineer",
    titleVi: "Kỹ sư An toàn Thông tin (Security Engineer)",
    descVi: "Củng cố hệ thống (Hardening), bảo mật đám mây, kiến trúc Zero Trust và DevSecOps.",
    descEn: "System hardening, cloud security architecture, Zero Trust and DevSecOps.",
  },
  {
    id: "security-analyst",
    domainId: "security",
    titleEn: "Security Analyst",
    titleVi: "Chuyên viên Phân tích Bảo mật (Security Analyst)",
    descVi: "Giám sát trung tâm SOC, phân tích log SIEM, điều tra mã độc và phản ứng sự cố.",
    descEn: "SOC operations, SIEM telemetry, malware triage and incident response.",
  },
  {
    id: "cybersecurity-specialist",
    domainId: "security",
    titleEn: "Cybersecurity Specialist",
    titleVi: "Chuyên gia An ninh mạng (Cybersecurity Specialist)",
    descVi: "Chiến lược an ninh mạng tổng thể, đánh giá lỗ hổng và bảo vệ dữ liệu doanh nghiệp.",
    descEn: "Holistic cyber defense, vulnerability management and enterprise data protection.",
  },
  {
    id: "ethical-hacker",
    domainId: "security",
    titleEn: "Ethical Hacker",
    titleVi: "Chuyên gia Đột nhập Đạo đức (Ethical Hacker)",
    descVi: "Mô phỏng tấn công Red Team, khai thác điểm yếu hệ thống và bảo mật ứng dụng.",
    descEn: "Red team adversary emulation, offensive security and vulnerability discovery.",
  },
  {
    id: "penetration-tester",
    domainId: "security",
    titleEn: "Penetration Tester",
    titleVi: "Chuyên viên Kiểm thử Xâm nhập (Penetration Tester)",
    descVi: "Đánh giá thâm nhập hệ thống mạng, ứng dụng web/mobile và báo cáo khắc phục.",
    descEn: "Network and web application penetration testing, exploitation and remediation.",
  },
  {
    id: "iam-analyst",
    domainId: "security",
    titleEn: "IAM Analyst",
    titleVi: "Chuyên viên Quản trị Danh tính (IAM Analyst)",
    descVi: "Quản trị danh tính và quyền truy cập (IAM), kiểm soát đặc quyền (PAM) và Single Sign-On.",
    descEn: "Identity & Access Management, role-based access control (RBAC), and SSO.",
  },
  {
    id: "grc-analyst",
    domainId: "security",
    titleEn: "GRC Analyst",
    titleVi: "Chuyên viên Quản trị Tuân thủ & Rủi ro (GRC Analyst)",
    descVi: "Tuân thủ tiêu chuẩn bảo mật quốc tế ISO 27001, SOC 2, PCI-DSS và quản trị rủi ro IT.",
    descEn: "Governance, Risk & Compliance, ISO 27001, SOC 2, and cybersecurity risk frameworks.",
  },
  {
    id: "cti-analyst",
    domainId: "security",
    titleEn: "CTI Analyst",
    titleVi: "Chuyên viên Tình báo Mối đe dọa (CTI Analyst)",
    descVi: "Thu thập và phân tích tình báo an ninh mạng (Cyber Threat Intelligence), APT Groups.",
    descEn: "Cyber Threat Intelligence, tracking threat actors and indicator analysis.",
  },

  // 5. Finance, Investment & Banking (5 roles)
  {
    id: "investment-banking",
    domainId: "finance",
    titleEn: "Investment Banking",
    titleVi: "Chuyên viên Ngân hàng Đầu tư (Investment Banking)",
    descVi: "Định giá M&A, mô hình DCF/LBO, vòng phỏng vấn Superday và thẩm định thương vụ.",
    descEn: "M&A valuation, DCF/LBO financial modeling, pitch books and deal execution.",
  },
  {
    id: "finance-and-strategy",
    domainId: "finance",
    titleEn: "Finance and Strategy",
    titleVi: "Chiến lược & Kế hoạch Tài chính (Finance and Strategy)",
    descVi: "Hoạch định ngân sách (FP&A), dự báo tài chính và tối ưu hóa cấu trúc vốn doanh nghiệp.",
    descEn: "Strategic financial planning (FP&A), corporate forecasting and capital structure.",
  },
  {
    id: "private-equity",
    domainId: "finance",
    titleEn: "Private Equity",
    titleVi: "Chuyên viên Quỹ Cổ phần Tư nhân (Private Equity)",
    descVi: "Đầu tư thâu tóm doanh nghiệp (Buyout), tối ưu hóa hoạt động và thoái vốn sinh lời.",
    descEn: "Leveraged buyouts (LBO), portfolio optimization and private investment memo.",
  },
  {
    id: "venture-capital",
    domainId: "finance",
    titleEn: "Venture Capital",
    titleVi: "Chuyên viên Quỹ Đầu tư Mạo hiểm (Venture Capital)",
    descVi: "Thẩm định startup công nghệ (Due Diligence), định giá vòng gọi vốn Seed/Series A.",
    descEn: "Startup due diligence, cap table modeling, term sheets and venture investing.",
  },
  {
    id: "quantitative-trader",
    domainId: "finance",
    titleEn: "Quantitative Trader",
    titleVi: "Chuyên viên Giao dịch Định lượng (Quantitative Trader)",
    descVi: "Vận hành chiến lược giao dịch tự động, quản trị rủi ro thị trường và thanh khoản.",
    descEn: "Algorithmic execution, market making, risk management and portfolio theory.",
  },

  // 6. UI/UX & Product Design (4 roles)
  {
    id: "product-designer",
    domainId: "design",
    titleEn: "Product Designer",
    titleVi: "Nhà thiết kế Sản phẩm (Product Designer)",
    descVi: "Thiết kế trải nghiệm trọn gói UI/UX, Design System, Prototyping và kiểm thử khả năng sử dụng.",
    descEn: "End-to-end UI/UX product design, Design Systems, prototyping and usability testing.",
  },
  {
    id: "visual-designer",
    domainId: "design",
    titleEn: "Visual Designer",
    titleVi: "Nhà thiết kế Trực quan (Visual Designer)",
    descVi: "Nghệ thuật thị giác, bộ nhận diện thương hiệu, thiết kế đồ họa tương tác và Typography.",
    descEn: "Visual identity, brand aesthetics, motion graphics and high-fidelity typography.",
  },
  {
    id: "user-researcher",
    domainId: "design",
    titleEn: "User Researcher",
    titleVi: "Chuyên viên Nghiên cứu Người dùng (User Researcher)",
    descVi: "Phỏng vấn người dùng định tính & định lượng, khảo sát thấu cảm và Journey Mapping.",
    descEn: "Qualitative & quantitative user research, usability testing and empathy studies.",
  },
  {
    id: "design-manager",
    domainId: "design",
    titleEn: "Design Manager",
    titleVi: "Quản lý Đội ngũ Thiết kế (Design Manager)",
    descVi: "Lãnh đạo đội ngũ thiết kế, định hình quy chuẩn Design Ops và kết nối tầm nhìn sản phẩm.",
    descEn: "Design leadership, DesignOps scalability and creative strategy.",
  },

  // 7. Business, Marketing & Talent (8 roles)
  {
    id: "marketing-manager",
    domainId: "business",
    titleEn: "Marketing Manager",
    titleVi: "Quản lý Tiếp thị (Marketing Manager)",
    descVi: "Chiến dịch tiếp thị tích hợp, định vị thương hiệu, quản trị ngân sách và đo lường ROI.",
    descEn: "Integrated marketing campaigns, brand positioning, budget allocation and ROI.",
  },
  {
    id: "product-marketing-manager",
    domainId: "business",
    titleEn: "Product Marketing Manager",
    titleVi: "Quản lý Tiếp thị Sản phẩm (Product Marketing Manager)",
    descVi: "Chiến lược ra mắt sản phẩm (Go-To-Market), định vị thông điệp và kích hoạt bán hàng.",
    descEn: "Go-to-market (GTM) launches, competitive positioning and sales enablement.",
  },
  {
    id: "growth-marketing-manager",
    domainId: "business",
    titleEn: "Growth Marketing Manager",
    titleVi: "Quản lý Tiếp thị Tăng trưởng (Growth Marketing Manager)",
    descVi: "Tối ưu hóa phễu tăng trưởng AARRR, Performance Ads, CRO và thử nghiệm tăng trưởng nhanh.",
    descEn: "AARRR growth funnel, performance acquisition, viral loops and CRO experimentation.",
  },
  {
    id: "sales-representative",
    domainId: "business",
    titleEn: "Sales Representative",
    titleVi: "Đại diện Bán hàng (Sales Representative)",
    descVi: "Tư vấn bán hàng, xử lý phản đối của khách hàng, đàm phán chốt hợp đồng và duy trì quan hệ.",
    descEn: "Consultative sales, objection handling, closing deals and revenue quota.",
  },
  {
    id: "business-development",
    domainId: "business",
    titleEn: "Business Development",
    titleVi: "Phát triển Kinh doanh (Business Development)",
    descVi: "Tìm kiếm cơ hội hợp tác chiến lược, mở rộng kênh phân phối và đàm phán liên minh.",
    descEn: "Strategic partnerships, commercial deal structuring and market expansion.",
  },
  {
    id: "account-manager",
    domainId: "business",
    titleEn: "Account Manager",
    titleVi: "Quản lý Khách hàng Doanh nghiệp (Account Manager)",
    descVi: "Chăm sóc khách hàng trọng điểm, gia hạn hợp đồng, Up-selling và Cross-selling.",
    descEn: "Key account management, retention, renewals, up-selling and client health.",
  },
  {
    id: "customer-success-manager",
    domainId: "business",
    titleEn: "Customer Success Manager",
    titleVi: "Quản lý Thành công Khách hàng (Customer Success Manager)",
    descVi: "Hỗ trợ khách hàng ứng dụng sản phẩm, giảm tỷ lệ rời bỏ (Churn) và gia tăng giá trị trọn đời.",
    descEn: "Product adoption, customer onboarding, churn reduction and Net Retention Rate.",
  },
  {
    id: "recruiter",
    domainId: "business",
    titleEn: "Recruiter",
    titleVi: "Chuyên viên Tuyển dụng (Recruiter / Talent Acquisition)",
    descVi: "Săn đầu người (Headhunting), xây dựng Talent Pool, phỏng vấn ứng viên và xây dựng thương hiệu tuyển dụng.",
    descEn: "Candidate sourcing, technical headhunting, interview assessment and employer branding.",
  },
];
