import type {
  DomainStatItem,
  RoleStatItem,
  LevelStatItem,
  AcquisitionChannelStat,
  OnboardedUserRecord,
  OnboardingSummaryStats,
} from "./types";

export const MOCK_ONBOARDING_SUMMARY: OnboardingSummaryStats = {
  total_users_started: 1620,
  total_users_completed: 1448,
  overall_completion_rate: 89.4,
  avg_time_seconds: 134, // 2m 14s
  top_domain_name: "Công nghệ thông tin (IT)",
  top_domain_percentage: 48.6,
  top_acquisition_channel: "Facebook (Ads & Groups)",
  top_channel_percentage: 30.0,
};

export const MOCK_ACQUISITION_CHANNELS: AcquisitionChannelStat[] = [
  {
    channel_key: "facebook",
    channel_name: "Facebook (Ads, Fanpage & Groups)",
    user_count: 434,
    percentage: 30.0,
    pro_conversion_rate: 18.5,
    growth_rate: "+24% MoM",
    color: "#1877f2",
    icon_name: "Facebook",
    description: "Quảng cáo Facebook Ads mục tiêu và thảo luận trên các hội nhóm IT & tìm việc làm.",
  },
  {
    channel_key: "tiktok",
    channel_name: "TikTok (Video ngắn & Tech Creators)",
    user_count: 362,
    percentage: 25.0,
    pro_conversion_rate: 14.2,
    growth_rate: "+48% MoM",
    color: "#fe2c55",
    icon_name: "Video",
    description: "Các video ngắn mock interview thực chiến, hướng dẫn phương pháp STAR từ creators gen Z.",
  },
  {
    channel_key: "youtube",
    channel_name: "YouTube (Tech Tutorials & Review)",
    user_count: 232,
    percentage: 16.0,
    pro_conversion_rate: 24.8,
    growth_rate: "+15% MoM",
    color: "#ff0000",
    icon_name: "Youtube",
    description: "Video chuyên sâu phân tích câu hỏi phỏng vấn doanh nghiệp và review công cụ AI Coach.",
  },
  {
    channel_key: "ai_recommendation",
    channel_name: "Gợi ý từ AI (ChatGPT, Claude, Perplexity)",
    user_count: 174,
    percentage: 12.0,
    pro_conversion_rate: 22.0,
    growth_rate: "+65% MoM",
    color: "#10b981",
    icon_name: "Sparkles",
    description: "Người dùng hỏi trợ lý AI về 'nền tảng luyện phỏng vấn AI tốt nhất' và được gợi ý Interviewly.",
  },
  {
    channel_key: "google_search",
    channel_name: "Google Search (SEO & Tìm kiếm tự nhiên)",
    user_count: 130,
    percentage: 9.0,
    pro_conversion_rate: 19.5,
    growth_rate: "+10% MoM",
    color: "#4285f4",
    icon_name: "Search",
    description: "Tìm kiếm từ khóa: 'phỏng vấn thử AI', 'câu hỏi phỏng vấn STAR', 'bảng điểm rubric'.",
  },
  {
    channel_key: "referral",
    channel_name: "Bạn bè & Đồng nghiệp giới thiệu",
    user_count: 87,
    percentage: 6.0,
    pro_conversion_rate: 28.5,
    growth_rate: "+18% MoM",
    color: "#8b5cf6",
    icon_name: "Users",
    description: "Ứng viên sau khi đỗ phỏng vấn giới thiệu trực tiếp cho bạn bè, câu lạc bộ đại học.",
  },
  {
    channel_key: "other",
    channel_name: "Kênh khác (Workshop, Sự kiện, Báo chí)",
    user_count: 29,
    percentage: 2.0,
    pro_conversion_rate: 12.0,
    growth_rate: "+5% MoM",
    color: "#6b7280",
    icon_name: "Globe",
    description: "Ngày hội việc làm Tech Day tại các trường đại học, tin bài báo chí công nghệ.",
  },
];

export const MOCK_DOMAIN_STATS: DomainStatItem[] = [
  {
    domain_id: 1,
    domain_name: "Công nghệ thông tin (IT)",
    code: "it_software",
    user_count: 704,
    percentage: 48.6,
    color: "#3b82f6",
    top_roles: ["Backend Engineer", "Frontend Developer", "Fullstack", "DevOps"],
  },
  {
    domain_id: 2,
    domain_name: "Marketing & Truyền thông",
    code: "marketing",
    user_count: 290,
    percentage: 20.0,
    color: "#ec4899",
    top_roles: ["Digital Marketing", "Content Creator", "SEO Specialist", "Brand Manager"],
  },
  {
    domain_id: 3,
    domain_name: "Tài chính & Ngân hàng",
    code: "finance_banking",
    user_count: 174,
    percentage: 12.0,
    color: "#10b981",
    top_roles: ["Financial Analyst", "Risk Manager", "Chuyên viên QHKH", "Kế toán"],
  },
  {
    domain_id: 4,
    domain_name: "Quản trị Kinh doanh & Sales",
    code: "business_sales",
    user_count: 145,
    percentage: 10.0,
    color: "#f59e0b",
    top_roles: ["B2B Sales", "Business Development", "Account Executive", "Chăm sóc KH"],
  },
  {
    domain_id: 5,
    domain_name: "Thiết kế Sản phẩm (UI/UX)",
    code: "design_uiux",
    user_count: 92,
    percentage: 6.4,
    color: "#8b5cf6",
    top_roles: ["UI/UX Designer", "Product Designer", "Graphic Designer"],
  },
  {
    domain_id: 6,
    domain_name: "Khác & Đang mở rộng",
    code: "others",
    user_count: 43,
    percentage: 3.0,
    color: "#6b7280",
    top_roles: ["Data Science", "Project Manager", "Logistics"],
  },
];

export const MOCK_ROLE_STATS: RoleStatItem[] = [
  {
    role_id: 1,
    role_name: "Backend Engineer (Node/Python/Go)",
    domain_name: "Công nghệ thông tin (IT)",
    user_count: 316,
    percentage: 21.8,
  },
  {
    role_id: 2,
    role_name: "Frontend Developer (React/Next.js)",
    domain_name: "Công nghệ thông tin (IT)",
    user_count: 262,
    percentage: 18.1,
  },
  {
    role_id: 3,
    role_name: "Fullstack Developer",
    domain_name: "Công nghệ thông tin (IT)",
    user_count: 187,
    percentage: 12.9,
  },
  {
    role_id: 4,
    role_name: "Data Analyst / Data Engineer",
    domain_name: "Công nghệ thông tin (IT)",
    user_count: 142,
    percentage: 9.8,
  },
  {
    role_id: 5,
    role_name: "Digital Marketing Specialist",
    domain_name: "Marketing & Truyền thông",
    user_count: 118,
    percentage: 8.1,
  },
  {
    role_id: 6,
    role_name: "Product Manager / Business Analyst",
    domain_name: "Quản trị Kinh doanh & Sales",
    user_count: 115,
    percentage: 7.9,
  },
  {
    role_id: 7,
    role_name: "Financial Analyst / Đầu tư",
    domain_name: "Tài chính & Ngân hàng",
    user_count: 98,
    percentage: 6.8,
  },
  {
    role_id: 8,
    role_name: "UI/UX Product Designer",
    domain_name: "Thiết kế Sản phẩm (UI/UX)",
    user_count: 92,
    percentage: 6.4,
  },
  {
    role_id: 9,
    role_name: "B2B Account Executive / Sales Rep",
    domain_name: "Quản trị Kinh doanh & Sales",
    user_count: 78,
    percentage: 5.4,
  },
  {
    role_id: 10,
    role_name: "Chuyên viên Tuyển dụng & HR",
    domain_name: "Quản trị Nhân sự",
    user_count: 40,
    percentage: 2.8,
  },
];

export const MOCK_LEVEL_STATS: LevelStatItem[] = [
  {
    level_key: "fresher",
    level_label: "Fresher / Mới tốt nghiệp (< 1 năm)",
    user_count: 426,
    percentage: 29.4,
    color: "#06b6d4",
  },
  {
    level_key: "junior",
    level_label: "Junior (1 - 2 năm kinh nghiệm)",
    user_count: 592,
    percentage: 40.9,
    color: "#3b82f6",
  },
  {
    level_key: "mid",
    level_label: "Middle (3 - 4 năm kinh nghiệm)",
    user_count: 294,
    percentage: 20.3,
    color: "#8b5cf6",
  },
  {
    level_key: "senior",
    level_label: "Senior / Tech Lead (5+ năm)",
    user_count: 136,
    percentage: 9.4,
    color: "#f59e0b",
  },
];

export const MOCK_ONBOARDED_USERS: OnboardedUserRecord[] = [
  {
    user_id: 101,
    full_name: "Nguyễn Hoàng Nam",
    email: "nam.nguyen@techcorp.vn",
    domain_name: "Công nghệ thông tin (IT)",
    role_name: "Backend Engineer",
    experience_level: "Senior (5+ năm)",
    target_goal: "Chuẩn bị phỏng vấn công ty công nghệ đa quốc gia",
    acquisition_channel: "youtube",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 112,
    completed_at: "2026-09-19T08:10:00Z",
    status: "completed",
  },
  {
    user_id: 102,
    full_name: "Trần Mai Anh",
    email: "maianh.tran@gmail.com",
    domain_name: "Marketing & Truyền thông",
    role_name: "Digital Marketing Specialist",
    experience_level: "Junior (1 - 2 năm)",
    target_goal: "Rèn luyện phản xạ phỏng vấn STAR tự tin",
    acquisition_channel: "tiktok",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 145,
    completed_at: "2026-09-19T07:45:00Z",
    status: "completed",
  },
  {
    user_id: 103,
    full_name: "Đặng Quang Huy",
    email: "huy.dang@fintech.io",
    domain_name: "Tài chính & Ngân hàng",
    role_name: "Financial Analyst",
    experience_level: "Middle (3 - 4 năm)",
    target_goal: "Luyện phỏng vấn tiếng Anh chuyên ngành tài chính",
    acquisition_channel: "ai_recommendation",
    language: "en",
    mic_verified: true,
    time_spent_seconds: 160,
    completed_at: "2026-09-19T07:15:00Z",
    status: "completed",
  },
  {
    user_id: 104,
    full_name: "Phạm Thùy Linh",
    email: "thuylinh.pham@designlab.co",
    domain_name: "Thiết kế Sản phẩm (UI/UX)",
    role_name: "UI/UX Product Designer",
    experience_level: "Fresher (< 1 năm)",
    target_goal: "Tìm việc làm đầu tiên sau khi tốt nghiệp",
    acquisition_channel: "facebook",
    language: "vi",
    mic_verified: false,
    time_spent_seconds: 98,
    completed_at: "2026-09-19T06:50:00Z",
    status: "completed",
  },
  {
    user_id: 105,
    full_name: "Vũ Tuấn Kiệt",
    email: "kiet.vu@fpt.com.vn",
    domain_name: "Công nghệ thông tin (IT)",
    role_name: "Fullstack Developer",
    experience_level: "Middle (3 - 4 năm)",
    target_goal: "Cải thiện kỹ năng diễn đạt giải pháp kiến trúc phần mềm",
    acquisition_channel: "google_search",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 130,
    completed_at: "2026-09-19T06:20:00Z",
    status: "completed",
  },
  {
    user_id: 106,
    full_name: "Lê Thị Hồng Nhung",
    email: "nhung.le@b2bsales.vn",
    domain_name: "Quản trị Kinh doanh & Sales",
    role_name: "B2B Account Executive",
    experience_level: "Senior (5+ năm)",
    target_goal: "Luyện đàm phán và thuyết trình với khách hàng doanh nghiệp",
    acquisition_channel: "referral",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 155,
    completed_at: "2026-09-19T05:40:00Z",
    status: "completed",
  },
  {
    user_id: 107,
    full_name: "Hoàng Đức Anh",
    email: "ducanh.hoang@gmail.com",
    domain_name: "Công nghệ thông tin (IT)",
    role_name: "Frontend Developer",
    experience_level: "Junior (1 - 2 năm)",
    target_goal: "Rèn luyện câu hỏi thuật toán và kiến thức React/Next.js",
    acquisition_channel: "tiktok",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 125,
    completed_at: "2026-09-19T05:05:00Z",
    status: "completed",
  },
  {
    user_id: 108,
    full_name: "Bùi Khánh Huyền",
    email: "huyen.bui@hcm.edu.vn",
    domain_name: "Marketing & Truyền thông",
    role_name: "Content Creator",
    experience_level: "Fresher (< 1 năm)",
    target_goal: "Thử sức phỏng vấn thử trước kỳ thực tập",
    acquisition_channel: "facebook",
    language: "vi",
    mic_verified: false,
    time_spent_seconds: 88,
    completed_at: "2026-09-19T04:30:00Z",
    status: "completed",
  },
  {
    user_id: 109,
    full_name: "Đỗ Minh Quân",
    email: "quan.do@cloudnative.dev",
    domain_name: "Công nghệ thông tin (IT)",
    role_name: "DevOps / SRE",
    experience_level: "Senior (5+ năm)",
    target_goal: "Nâng cao năng lực giải quyết sự cố hạ tầng Kubernetes/AWS",
    acquisition_channel: "ai_recommendation",
    language: "en",
    mic_verified: true,
    time_spent_seconds: 140,
    completed_at: "2026-09-19T03:55:00Z",
    status: "completed",
  },
  {
    user_id: 110,
    full_name: "Trương Mỹ Duyên",
    email: "myduyen.truong@bankplus.vn",
    domain_name: "Tài chính & Ngân hàng",
    role_name: "Chuyên viên QHKH Doanh nghiệp",
    experience_level: "Junior (1 - 2 năm)",
    target_goal: "Chuẩn bị thi tuyển vị trí chuyên viên ngân hàng thương mại",
    acquisition_channel: "referral",
    language: "vi",
    mic_verified: true,
    time_spent_seconds: 135,
    completed_at: "2026-09-19T03:10:00Z",
    status: "completed",
  },
];